<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NewUserType</name>
   <tag></tag>
   <elementGuidId>d95b53c3-f56a-4284-a62a-780858b6d2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cdk-overlay-18&quot;]/nz-modal/div/div[2]/div[1]/div/div[1]/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'ng-star-inserted' and (text() = '新建用户类型' or . = '新建用户类型')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>新建用户类型</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-21&quot;)/nz-modal[1]/div[1]/div[@class=&quot;ant-modal-wrap&quot;]/div[@class=&quot;ant-modal&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-header ng-star-inserted&quot;]/div[@class=&quot;ant-modal-title&quot;]/div[@class=&quot;ng-star-inserted&quot;]</value>
   </webElementProperties>
</WebElementEntity>
